apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-python
  template:
    metadata:
      labels:
        app: ubuntu-python
    spec:
      containers:
        - name: ubuntu-python
          image: localhost:5001/ubuntu-python
          ports:
            - containerPort: 8080
